// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjFoGOCB8FlGGur4-VjCqPvNUcs7d-BQ',
    appId: '1:393724708373:android:1f615b82185fa9aa94701c',
    messagingSenderId: '393724708373',
    projectId: 'tradingcex',
    storageBucket: 'tradingcex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YiVlQnHKVHtKXUm7YqjqnpQDcocl5-Q',
    appId: '1:393724708373:ios:9e87e27e2dc0383b94701c',
    messagingSenderId: '393724708373',
    projectId: 'tradingcex',
    storageBucket: 'tradingcex.firebasestorage.app',
    androidClientId: '393724708373-itui0o61prhc8md4ce94ulqo3fu0gk19.apps.googleusercontent.com',
    iosClientId: '393724708373-m2uiv5kgfslrcu18l59hnr23jjt0546b.apps.googleusercontent.com',
    iosBundleId: 'com.trading.cex',
  );

}